from django.db import models
from market_data.models import Candle


class Signal(models.Model):
    """
    Represents a multi-timeframe trading signal generated by the AI.
    This model is designed to store the final, structured AI response.
    """

    class SignalDirection(models.TextChoices):
        BULLISH = 'BULLISH', 'Bullish'
        BEARISH = 'BEARISH', 'Bearish'
        NEUTRAL = 'NEUTRAL', 'Neutral'

    candle = models.OneToOneField(Candle, on_delete=models.CASCADE, related_name='signal')

    # --- Predictions for 4 timeframes ---
    direction_next_candle = models.CharField(max_length=10, choices=SignalDirection.choices)
    confidence_next_candle = models.DecimalField(max_digits=5, decimal_places=2)

    direction_3rd_candle = models.CharField(max_length=10, choices=SignalDirection.choices)
    confidence_3rd_candle = models.DecimalField(max_digits=5, decimal_places=2)

    direction_5th_candle = models.CharField(max_length=10, choices=SignalDirection.choices)
    confidence_5th_candle = models.DecimalField(max_digits=5, decimal_places=2)

    direction_10th_candle = models.CharField(max_length=10, choices=SignalDirection.choices)
    confidence_10th_candle = models.DecimalField(max_digits=5, decimal_places=2)

    # --- AI-generated textual analysis ---
    probability_text = models.TextField()
    risk_text = models.TextField()

    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Signal for {self.candle.symbol.name} @ {self.candle.timestamp}"

    class Meta:
        ordering = ['-candle__timestamp']
